name: ci
on:
  push:

jobs:
  image-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/nginxtest:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ github.actor }}/nginxtest:test
            
      - run: |
          sudo apt-get update
          sudo apt-get install docker
          sudo docker build -t asy1ess/nginxtest:test .
          sudo docker ps -a
          sudo docker images
          sudo docker push asy1ess/nginxtest:test
          
      
